#!/usr/bin/env bash
#---------------------------------------------------------------------
# Bashplate environment init script
#
#---------------------------------------------------------------------
# Use:
# Run this from .bashrc file.
#
# source pathToThisFile/bp_init
#
#


#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
BP_SELF_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#---------------------------------------------------------------------

bpSettingsDir=~/.config/bashplates
bpSettings=${bpSettingsDir}/bashplates.conf

addSetting() {
  echo "# "${3}    >> ${bpSettings}
	echo ${1}"=\""${2}"\"" >> ${bpSettings}
	echo >> ${bpSettings}
}
		
createSettings() {
		
  echo "Creating new bashplates settings file. ${bpSettings}"
	mkdir -p ${bpSettingsDir}
	
	echo "# " >> ${bpSettings}
	echo "# Bashplates common settings" > ${bpSettings}
	echo "# " >> ${bpSettings}
	echo      >> ${bpSettings}
			
	addSetting "BP_NAME"    "John Doe"        "Name of user"
	addSetting "BP_EMAIL"   "JohnDoe@foo.bar" "Email of user"
	addSetting "BP_EDITOR"  "vi"              "Default editor"
	addSetting "BP_LICENSE" "MIT"             "Default project license"
	addSetting "BP_ORG"     "ACME"            "Default organisation"
	addSetting "BP_DIFF"    "meld"            "Default diff program"
}
													
bpLoadSettings() {
  if [ -n "${bpSettings}" ]; then
    if [ -e ${bpSettings} ]; then
      source ${bpSettings}
    else
      createSettings
      source ${bpSettings}
    fi
  fi
	
	export BP_NAME
	export BP_EMAIL
	export BP_EDITOR
	export BP_LICENSE
	export BP_ORG
	export BP_PATH
} 


bpLoadSettings
																			
# Add bashplate dir to search path
export PATH=${PATH}:${BP_SELF_DIR}

# Add variable pointing to bashplate dir
export BP_PATH=${BP_SELF_DIR}

# Add alias for quick access to bashplate dir
#alias bpd='cd ${BP_SELF_DIR}'
#alias bplsd="bprc lsd"

_bp_completions() {
  COMPREPLY=$(bp help)
}

_bpdev_completions() {
  COMPREPLY=$(bpdev completion)
}

#complete -F _bp_completions bp
#complete -F _bpdev_completions bpdev


if [ -f "${BP_SELF_DIR}/DEV" ]; then
#  BP_DEV=1
  alias cdb='cd "${BP_SELF_DIR}"'
fi

# Indicated that initscript was run
export BP_INIT_RUN=1


