#!/usr/bin/env bash
#---------------------------------------------------------------------
#
#  __NAME__
#
#  [Description]
#    __DESC__
#
#  [Author] 
#    __AUTHOR__
#
#  [Date]
#    __DATE__
#    
#---------------------------------------------------------------------
#

#set -o xtrace   # Display commands as they are executed
#set -o pipefail # Exit script when pipe fails

# Directory where script is located
scriptPath=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#---------------------------------------------------------------------

